homework week 3 - version 0.0.1
HackYourFuture-CPH/node.js pull request #20
Opened 2017-10-14 18:47 UTC by jawkha

In trying to use an external database(MongoDB) for storing the contact list, I have deviated a lot from the original requirements of the work. In this iteration, we can use the API to perform basic CRUD operations. Input validation only takes place at the db level and is not comprehensive enough. In the next iteration, I will address this.
I will also update the PUT and DELETE operations to retrieve records from the database using fields other than ID.

2017-10-15 15:46 UTC, r0hitsharma requested changes
I would really recommend you doing this homework with file instead, because I think Mongoose, being a well written library takes care of most of the conceptual issues you would've otherwise needed to consider.

For added challenge, could you try and implement an immutable `id` for the objects? You could consider two strategies: increments or hashing (this would make more sense when you work with DB's further).

2017-10-15 15:46 UTC, r0hitsharma commented on week3/homework/src/routes/api.js
> +    Contact.findByIdAndUpdate({_id: req.params.id}, req.body).then(function(){
Would you please refactor the nested `.next()` functions using Promise?

2017-10-18 09:10 UTC, jawkha commented
Hi Rohit, thanks for the feedback. I'll redo it without using MongoDB.

2017-10-21 20:32 UTC, jawkha commented
I have uploaded a working but still unfinished version of the final project for Node module. I couldn't get back to making the requested changes for week 3 homework during this week. Will do it during the next week and upload them.

2019-07-12 13:55 UTC, closed without merging