Substitute occurrences of master by main
HackYourFuture-CPH/node.js pull request #66
Opened 2021-12-18 19:22 UTC by martamatos

2021-12-22 11:29 UTC, dpfernandes requested changes

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "A Nightmare on Elm Street 4: The Dream main",
I think this is a movie title :) 

Should we replace the whole title @martamatos ?

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "mainminds",
The same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "mains of the Universe",
the same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The Beastmain",
the same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The main",
the same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The main of Disguise",
the same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The Pagemain",
the same here

2021-12-22 11:29 UTC, dpfernandes commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "Wishmain",
the same here

2022-02-04 13:24 UTC, CK-HYF-DK commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The Pagemain",
this one is kinda funny

2022-02-04 13:25 UTC, CK-HYF-DK commented on week2/exercise-template/src/backend/data/movies.json
> +        "title": "The main",
Another Paul Thomas Anderson classic :D

2022-02-25 23:40 UTC, merged